// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exhook.proto

package com.thpower.emqx.java;

/**
 * Protobuf type {@code emqx.exhook.v2.ClientInfo}
 */
public final class ClientInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:emqx.exhook.v2.ClientInfo)
    ClientInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ClientInfo.newBuilder() to construct.
  private ClientInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ClientInfo() {
    node_ = "";
    clientid_ = "";
    username_ = "";
    password_ = "";
    peerhost_ = "";
    protocol_ = "";
    mountpoint_ = "";
    cn_ = "";
    dn_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ClientInfo();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ClientInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            node_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            clientid_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            username_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            password_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            peerhost_ = s;
            break;
          }
          case 48: {

            sockport_ = input.readUInt32();
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            protocol_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            mountpoint_ = s;
            break;
          }
          case 72: {

            isSuperuser_ = input.readBool();
            break;
          }
          case 80: {

            anonymous_ = input.readBool();
            break;
          }
          case 90: {
            java.lang.String s = input.readStringRequireUtf8();

            cn_ = s;
            break;
          }
          case 98: {
            java.lang.String s = input.readStringRequireUtf8();

            dn_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.thpower.emqx.java.EmqxExHookProto.internal_static_emqx_exhook_v2_ClientInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.thpower.emqx.java.EmqxExHookProto.internal_static_emqx_exhook_v2_ClientInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.thpower.emqx.java.ClientInfo.class, com.thpower.emqx.java.ClientInfo.Builder.class);
  }

  public static final int NODE_FIELD_NUMBER = 1;
  private volatile java.lang.Object node_;
  /**
   * <code>string node = 1;</code>
   * @return The node.
   */
  @java.lang.Override
  public java.lang.String getNode() {
    java.lang.Object ref = node_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      node_ = s;
      return s;
    }
  }
  /**
   * <code>string node = 1;</code>
   * @return The bytes for node.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNodeBytes() {
    java.lang.Object ref = node_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      node_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CLIENTID_FIELD_NUMBER = 2;
  private volatile java.lang.Object clientid_;
  /**
   * <code>string clientid = 2;</code>
   * @return The clientid.
   */
  @java.lang.Override
  public java.lang.String getClientid() {
    java.lang.Object ref = clientid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      clientid_ = s;
      return s;
    }
  }
  /**
   * <code>string clientid = 2;</code>
   * @return The bytes for clientid.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getClientidBytes() {
    java.lang.Object ref = clientid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      clientid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USERNAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object username_;
  /**
   * <code>string username = 3;</code>
   * @return The username.
   */
  @java.lang.Override
  public java.lang.String getUsername() {
    java.lang.Object ref = username_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      username_ = s;
      return s;
    }
  }
  /**
   * <code>string username = 3;</code>
   * @return The bytes for username.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUsernameBytes() {
    java.lang.Object ref = username_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      username_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PASSWORD_FIELD_NUMBER = 4;
  private volatile java.lang.Object password_;
  /**
   * <code>string password = 4;</code>
   * @return The password.
   */
  @java.lang.Override
  public java.lang.String getPassword() {
    java.lang.Object ref = password_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      password_ = s;
      return s;
    }
  }
  /**
   * <code>string password = 4;</code>
   * @return The bytes for password.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPasswordBytes() {
    java.lang.Object ref = password_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      password_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PEERHOST_FIELD_NUMBER = 5;
  private volatile java.lang.Object peerhost_;
  /**
   * <code>string peerhost = 5;</code>
   * @return The peerhost.
   */
  @java.lang.Override
  public java.lang.String getPeerhost() {
    java.lang.Object ref = peerhost_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      peerhost_ = s;
      return s;
    }
  }
  /**
   * <code>string peerhost = 5;</code>
   * @return The bytes for peerhost.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPeerhostBytes() {
    java.lang.Object ref = peerhost_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      peerhost_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SOCKPORT_FIELD_NUMBER = 6;
  private int sockport_;
  /**
   * <code>uint32 sockport = 6;</code>
   * @return The sockport.
   */
  @java.lang.Override
  public int getSockport() {
    return sockport_;
  }

  public static final int PROTOCOL_FIELD_NUMBER = 7;
  private volatile java.lang.Object protocol_;
  /**
   * <code>string protocol = 7;</code>
   * @return The protocol.
   */
  @java.lang.Override
  public java.lang.String getProtocol() {
    java.lang.Object ref = protocol_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      protocol_ = s;
      return s;
    }
  }
  /**
   * <code>string protocol = 7;</code>
   * @return The bytes for protocol.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProtocolBytes() {
    java.lang.Object ref = protocol_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      protocol_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MOUNTPOINT_FIELD_NUMBER = 8;
  private volatile java.lang.Object mountpoint_;
  /**
   * <code>string mountpoint = 8;</code>
   * @return The mountpoint.
   */
  @java.lang.Override
  public java.lang.String getMountpoint() {
    java.lang.Object ref = mountpoint_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      mountpoint_ = s;
      return s;
    }
  }
  /**
   * <code>string mountpoint = 8;</code>
   * @return The bytes for mountpoint.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMountpointBytes() {
    java.lang.Object ref = mountpoint_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      mountpoint_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IS_SUPERUSER_FIELD_NUMBER = 9;
  private boolean isSuperuser_;
  /**
   * <code>bool is_superuser = 9;</code>
   * @return The isSuperuser.
   */
  @java.lang.Override
  public boolean getIsSuperuser() {
    return isSuperuser_;
  }

  public static final int ANONYMOUS_FIELD_NUMBER = 10;
  private boolean anonymous_;
  /**
   * <code>bool anonymous = 10;</code>
   * @return The anonymous.
   */
  @java.lang.Override
  public boolean getAnonymous() {
    return anonymous_;
  }

  public static final int CN_FIELD_NUMBER = 11;
  private volatile java.lang.Object cn_;
  /**
   * <pre>
   * common name of client TLS cert
   * </pre>
   *
   * <code>string cn = 11;</code>
   * @return The cn.
   */
  @java.lang.Override
  public java.lang.String getCn() {
    java.lang.Object ref = cn_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cn_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * common name of client TLS cert
   * </pre>
   *
   * <code>string cn = 11;</code>
   * @return The bytes for cn.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCnBytes() {
    java.lang.Object ref = cn_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cn_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DN_FIELD_NUMBER = 12;
  private volatile java.lang.Object dn_;
  /**
   * <pre>
   * subject of client TLS cert
   * </pre>
   *
   * <code>string dn = 12;</code>
   * @return The dn.
   */
  @java.lang.Override
  public java.lang.String getDn() {
    java.lang.Object ref = dn_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dn_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * subject of client TLS cert
   * </pre>
   *
   * <code>string dn = 12;</code>
   * @return The bytes for dn.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDnBytes() {
    java.lang.Object ref = dn_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dn_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getNodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, node_);
    }
    if (!getClientidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, clientid_);
    }
    if (!getUsernameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, username_);
    }
    if (!getPasswordBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, password_);
    }
    if (!getPeerhostBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, peerhost_);
    }
    if (sockport_ != 0) {
      output.writeUInt32(6, sockport_);
    }
    if (!getProtocolBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, protocol_);
    }
    if (!getMountpointBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, mountpoint_);
    }
    if (isSuperuser_ != false) {
      output.writeBool(9, isSuperuser_);
    }
    if (anonymous_ != false) {
      output.writeBool(10, anonymous_);
    }
    if (!getCnBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, cn_);
    }
    if (!getDnBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, dn_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getNodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, node_);
    }
    if (!getClientidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, clientid_);
    }
    if (!getUsernameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, username_);
    }
    if (!getPasswordBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, password_);
    }
    if (!getPeerhostBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, peerhost_);
    }
    if (sockport_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(6, sockport_);
    }
    if (!getProtocolBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, protocol_);
    }
    if (!getMountpointBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, mountpoint_);
    }
    if (isSuperuser_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(9, isSuperuser_);
    }
    if (anonymous_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(10, anonymous_);
    }
    if (!getCnBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, cn_);
    }
    if (!getDnBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, dn_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.thpower.emqx.java.ClientInfo)) {
      return super.equals(obj);
    }
    com.thpower.emqx.java.ClientInfo other = (com.thpower.emqx.java.ClientInfo) obj;

    if (!getNode()
        .equals(other.getNode())) return false;
    if (!getClientid()
        .equals(other.getClientid())) return false;
    if (!getUsername()
        .equals(other.getUsername())) return false;
    if (!getPassword()
        .equals(other.getPassword())) return false;
    if (!getPeerhost()
        .equals(other.getPeerhost())) return false;
    if (getSockport()
        != other.getSockport()) return false;
    if (!getProtocol()
        .equals(other.getProtocol())) return false;
    if (!getMountpoint()
        .equals(other.getMountpoint())) return false;
    if (getIsSuperuser()
        != other.getIsSuperuser()) return false;
    if (getAnonymous()
        != other.getAnonymous()) return false;
    if (!getCn()
        .equals(other.getCn())) return false;
    if (!getDn()
        .equals(other.getDn())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NODE_FIELD_NUMBER;
    hash = (53 * hash) + getNode().hashCode();
    hash = (37 * hash) + CLIENTID_FIELD_NUMBER;
    hash = (53 * hash) + getClientid().hashCode();
    hash = (37 * hash) + USERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getUsername().hashCode();
    hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
    hash = (53 * hash) + getPassword().hashCode();
    hash = (37 * hash) + PEERHOST_FIELD_NUMBER;
    hash = (53 * hash) + getPeerhost().hashCode();
    hash = (37 * hash) + SOCKPORT_FIELD_NUMBER;
    hash = (53 * hash) + getSockport();
    hash = (37 * hash) + PROTOCOL_FIELD_NUMBER;
    hash = (53 * hash) + getProtocol().hashCode();
    hash = (37 * hash) + MOUNTPOINT_FIELD_NUMBER;
    hash = (53 * hash) + getMountpoint().hashCode();
    hash = (37 * hash) + IS_SUPERUSER_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsSuperuser());
    hash = (37 * hash) + ANONYMOUS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getAnonymous());
    hash = (37 * hash) + CN_FIELD_NUMBER;
    hash = (53 * hash) + getCn().hashCode();
    hash = (37 * hash) + DN_FIELD_NUMBER;
    hash = (53 * hash) + getDn().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.thpower.emqx.java.ClientInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.thpower.emqx.java.ClientInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.thpower.emqx.java.ClientInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.thpower.emqx.java.ClientInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.thpower.emqx.java.ClientInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.thpower.emqx.java.ClientInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.thpower.emqx.java.ClientInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.thpower.emqx.java.ClientInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.thpower.emqx.java.ClientInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.thpower.emqx.java.ClientInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.thpower.emqx.java.ClientInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.thpower.emqx.java.ClientInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.thpower.emqx.java.ClientInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code emqx.exhook.v2.ClientInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:emqx.exhook.v2.ClientInfo)
      com.thpower.emqx.java.ClientInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.thpower.emqx.java.EmqxExHookProto.internal_static_emqx_exhook_v2_ClientInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.thpower.emqx.java.EmqxExHookProto.internal_static_emqx_exhook_v2_ClientInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.thpower.emqx.java.ClientInfo.class, com.thpower.emqx.java.ClientInfo.Builder.class);
    }

    // Construct using com.thpower.emqx.java.ClientInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      node_ = "";

      clientid_ = "";

      username_ = "";

      password_ = "";

      peerhost_ = "";

      sockport_ = 0;

      protocol_ = "";

      mountpoint_ = "";

      isSuperuser_ = false;

      anonymous_ = false;

      cn_ = "";

      dn_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.thpower.emqx.java.EmqxExHookProto.internal_static_emqx_exhook_v2_ClientInfo_descriptor;
    }

    @java.lang.Override
    public com.thpower.emqx.java.ClientInfo getDefaultInstanceForType() {
      return com.thpower.emqx.java.ClientInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.thpower.emqx.java.ClientInfo build() {
      com.thpower.emqx.java.ClientInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.thpower.emqx.java.ClientInfo buildPartial() {
      com.thpower.emqx.java.ClientInfo result = new com.thpower.emqx.java.ClientInfo(this);
      result.node_ = node_;
      result.clientid_ = clientid_;
      result.username_ = username_;
      result.password_ = password_;
      result.peerhost_ = peerhost_;
      result.sockport_ = sockport_;
      result.protocol_ = protocol_;
      result.mountpoint_ = mountpoint_;
      result.isSuperuser_ = isSuperuser_;
      result.anonymous_ = anonymous_;
      result.cn_ = cn_;
      result.dn_ = dn_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.thpower.emqx.java.ClientInfo) {
        return mergeFrom((com.thpower.emqx.java.ClientInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.thpower.emqx.java.ClientInfo other) {
      if (other == com.thpower.emqx.java.ClientInfo.getDefaultInstance()) return this;
      if (!other.getNode().isEmpty()) {
        node_ = other.node_;
        onChanged();
      }
      if (!other.getClientid().isEmpty()) {
        clientid_ = other.clientid_;
        onChanged();
      }
      if (!other.getUsername().isEmpty()) {
        username_ = other.username_;
        onChanged();
      }
      if (!other.getPassword().isEmpty()) {
        password_ = other.password_;
        onChanged();
      }
      if (!other.getPeerhost().isEmpty()) {
        peerhost_ = other.peerhost_;
        onChanged();
      }
      if (other.getSockport() != 0) {
        setSockport(other.getSockport());
      }
      if (!other.getProtocol().isEmpty()) {
        protocol_ = other.protocol_;
        onChanged();
      }
      if (!other.getMountpoint().isEmpty()) {
        mountpoint_ = other.mountpoint_;
        onChanged();
      }
      if (other.getIsSuperuser() != false) {
        setIsSuperuser(other.getIsSuperuser());
      }
      if (other.getAnonymous() != false) {
        setAnonymous(other.getAnonymous());
      }
      if (!other.getCn().isEmpty()) {
        cn_ = other.cn_;
        onChanged();
      }
      if (!other.getDn().isEmpty()) {
        dn_ = other.dn_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.thpower.emqx.java.ClientInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.thpower.emqx.java.ClientInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object node_ = "";
    /**
     * <code>string node = 1;</code>
     * @return The node.
     */
    public java.lang.String getNode() {
      java.lang.Object ref = node_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        node_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string node = 1;</code>
     * @return The bytes for node.
     */
    public com.google.protobuf.ByteString
        getNodeBytes() {
      java.lang.Object ref = node_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        node_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string node = 1;</code>
     * @param value The node to set.
     * @return This builder for chaining.
     */
    public Builder setNode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      node_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string node = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearNode() {
      
      node_ = getDefaultInstance().getNode();
      onChanged();
      return this;
    }
    /**
     * <code>string node = 1;</code>
     * @param value The bytes for node to set.
     * @return This builder for chaining.
     */
    public Builder setNodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      node_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object clientid_ = "";
    /**
     * <code>string clientid = 2;</code>
     * @return The clientid.
     */
    public java.lang.String getClientid() {
      java.lang.Object ref = clientid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string clientid = 2;</code>
     * @return The bytes for clientid.
     */
    public com.google.protobuf.ByteString
        getClientidBytes() {
      java.lang.Object ref = clientid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string clientid = 2;</code>
     * @param value The clientid to set.
     * @return This builder for chaining.
     */
    public Builder setClientid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      clientid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string clientid = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearClientid() {
      
      clientid_ = getDefaultInstance().getClientid();
      onChanged();
      return this;
    }
    /**
     * <code>string clientid = 2;</code>
     * @param value The bytes for clientid to set.
     * @return This builder for chaining.
     */
    public Builder setClientidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      clientid_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object username_ = "";
    /**
     * <code>string username = 3;</code>
     * @return The username.
     */
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        username_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string username = 3;</code>
     * @return The bytes for username.
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string username = 3;</code>
     * @param value The username to set.
     * @return This builder for chaining.
     */
    public Builder setUsername(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      username_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string username = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearUsername() {
      
      username_ = getDefaultInstance().getUsername();
      onChanged();
      return this;
    }
    /**
     * <code>string username = 3;</code>
     * @param value The bytes for username to set.
     * @return This builder for chaining.
     */
    public Builder setUsernameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      username_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object password_ = "";
    /**
     * <code>string password = 4;</code>
     * @return The password.
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        password_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string password = 4;</code>
     * @return The bytes for password.
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string password = 4;</code>
     * @param value The password to set.
     * @return This builder for chaining.
     */
    public Builder setPassword(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      password_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string password = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPassword() {
      
      password_ = getDefaultInstance().getPassword();
      onChanged();
      return this;
    }
    /**
     * <code>string password = 4;</code>
     * @param value The bytes for password to set.
     * @return This builder for chaining.
     */
    public Builder setPasswordBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      password_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object peerhost_ = "";
    /**
     * <code>string peerhost = 5;</code>
     * @return The peerhost.
     */
    public java.lang.String getPeerhost() {
      java.lang.Object ref = peerhost_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        peerhost_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string peerhost = 5;</code>
     * @return The bytes for peerhost.
     */
    public com.google.protobuf.ByteString
        getPeerhostBytes() {
      java.lang.Object ref = peerhost_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        peerhost_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string peerhost = 5;</code>
     * @param value The peerhost to set.
     * @return This builder for chaining.
     */
    public Builder setPeerhost(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      peerhost_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string peerhost = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPeerhost() {
      
      peerhost_ = getDefaultInstance().getPeerhost();
      onChanged();
      return this;
    }
    /**
     * <code>string peerhost = 5;</code>
     * @param value The bytes for peerhost to set.
     * @return This builder for chaining.
     */
    public Builder setPeerhostBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      peerhost_ = value;
      onChanged();
      return this;
    }

    private int sockport_ ;
    /**
     * <code>uint32 sockport = 6;</code>
     * @return The sockport.
     */
    @java.lang.Override
    public int getSockport() {
      return sockport_;
    }
    /**
     * <code>uint32 sockport = 6;</code>
     * @param value The sockport to set.
     * @return This builder for chaining.
     */
    public Builder setSockport(int value) {
      
      sockport_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 sockport = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearSockport() {
      
      sockport_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object protocol_ = "";
    /**
     * <code>string protocol = 7;</code>
     * @return The protocol.
     */
    public java.lang.String getProtocol() {
      java.lang.Object ref = protocol_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        protocol_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string protocol = 7;</code>
     * @return The bytes for protocol.
     */
    public com.google.protobuf.ByteString
        getProtocolBytes() {
      java.lang.Object ref = protocol_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        protocol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string protocol = 7;</code>
     * @param value The protocol to set.
     * @return This builder for chaining.
     */
    public Builder setProtocol(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      protocol_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string protocol = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearProtocol() {
      
      protocol_ = getDefaultInstance().getProtocol();
      onChanged();
      return this;
    }
    /**
     * <code>string protocol = 7;</code>
     * @param value The bytes for protocol to set.
     * @return This builder for chaining.
     */
    public Builder setProtocolBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      protocol_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object mountpoint_ = "";
    /**
     * <code>string mountpoint = 8;</code>
     * @return The mountpoint.
     */
    public java.lang.String getMountpoint() {
      java.lang.Object ref = mountpoint_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mountpoint_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string mountpoint = 8;</code>
     * @return The bytes for mountpoint.
     */
    public com.google.protobuf.ByteString
        getMountpointBytes() {
      java.lang.Object ref = mountpoint_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mountpoint_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string mountpoint = 8;</code>
     * @param value The mountpoint to set.
     * @return This builder for chaining.
     */
    public Builder setMountpoint(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      mountpoint_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string mountpoint = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearMountpoint() {
      
      mountpoint_ = getDefaultInstance().getMountpoint();
      onChanged();
      return this;
    }
    /**
     * <code>string mountpoint = 8;</code>
     * @param value The bytes for mountpoint to set.
     * @return This builder for chaining.
     */
    public Builder setMountpointBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      mountpoint_ = value;
      onChanged();
      return this;
    }

    private boolean isSuperuser_ ;
    /**
     * <code>bool is_superuser = 9;</code>
     * @return The isSuperuser.
     */
    @java.lang.Override
    public boolean getIsSuperuser() {
      return isSuperuser_;
    }
    /**
     * <code>bool is_superuser = 9;</code>
     * @param value The isSuperuser to set.
     * @return This builder for chaining.
     */
    public Builder setIsSuperuser(boolean value) {
      
      isSuperuser_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool is_superuser = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsSuperuser() {
      
      isSuperuser_ = false;
      onChanged();
      return this;
    }

    private boolean anonymous_ ;
    /**
     * <code>bool anonymous = 10;</code>
     * @return The anonymous.
     */
    @java.lang.Override
    public boolean getAnonymous() {
      return anonymous_;
    }
    /**
     * <code>bool anonymous = 10;</code>
     * @param value The anonymous to set.
     * @return This builder for chaining.
     */
    public Builder setAnonymous(boolean value) {
      
      anonymous_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool anonymous = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearAnonymous() {
      
      anonymous_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object cn_ = "";
    /**
     * <pre>
     * common name of client TLS cert
     * </pre>
     *
     * <code>string cn = 11;</code>
     * @return The cn.
     */
    public java.lang.String getCn() {
      java.lang.Object ref = cn_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cn_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * common name of client TLS cert
     * </pre>
     *
     * <code>string cn = 11;</code>
     * @return The bytes for cn.
     */
    public com.google.protobuf.ByteString
        getCnBytes() {
      java.lang.Object ref = cn_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * common name of client TLS cert
     * </pre>
     *
     * <code>string cn = 11;</code>
     * @param value The cn to set.
     * @return This builder for chaining.
     */
    public Builder setCn(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cn_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * common name of client TLS cert
     * </pre>
     *
     * <code>string cn = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearCn() {
      
      cn_ = getDefaultInstance().getCn();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * common name of client TLS cert
     * </pre>
     *
     * <code>string cn = 11;</code>
     * @param value The bytes for cn to set.
     * @return This builder for chaining.
     */
    public Builder setCnBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cn_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object dn_ = "";
    /**
     * <pre>
     * subject of client TLS cert
     * </pre>
     *
     * <code>string dn = 12;</code>
     * @return The dn.
     */
    public java.lang.String getDn() {
      java.lang.Object ref = dn_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dn_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * subject of client TLS cert
     * </pre>
     *
     * <code>string dn = 12;</code>
     * @return The bytes for dn.
     */
    public com.google.protobuf.ByteString
        getDnBytes() {
      java.lang.Object ref = dn_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * subject of client TLS cert
     * </pre>
     *
     * <code>string dn = 12;</code>
     * @param value The dn to set.
     * @return This builder for chaining.
     */
    public Builder setDn(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dn_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * subject of client TLS cert
     * </pre>
     *
     * <code>string dn = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearDn() {
      
      dn_ = getDefaultInstance().getDn();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * subject of client TLS cert
     * </pre>
     *
     * <code>string dn = 12;</code>
     * @param value The bytes for dn to set.
     * @return This builder for chaining.
     */
    public Builder setDnBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dn_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:emqx.exhook.v2.ClientInfo)
  }

  // @@protoc_insertion_point(class_scope:emqx.exhook.v2.ClientInfo)
  private static final com.thpower.emqx.java.ClientInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.thpower.emqx.java.ClientInfo();
  }

  public static com.thpower.emqx.java.ClientInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ClientInfo>
      PARSER = new com.google.protobuf.AbstractParser<ClientInfo>() {
    @java.lang.Override
    public ClientInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ClientInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ClientInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ClientInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.thpower.emqx.java.ClientInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

