// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exhook.proto

package com.thpower.emqx.java;

public interface ClientSubscribeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:emqx.exhook.v2.ClientSubscribeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.emqx.exhook.v2.ClientInfo clientinfo = 1;</code>
   * @return Whether the clientinfo field is set.
   */
  boolean hasClientinfo();
  /**
   * <code>.emqx.exhook.v2.ClientInfo clientinfo = 1;</code>
   * @return The clientinfo.
   */
  com.thpower.emqx.java.ClientInfo getClientinfo();
  /**
   * <code>.emqx.exhook.v2.ClientInfo clientinfo = 1;</code>
   */
  com.thpower.emqx.java.ClientInfoOrBuilder getClientinfoOrBuilder();

  /**
   * <code>repeated .emqx.exhook.v2.Property props = 2;</code>
   */
  java.util.List<com.thpower.emqx.java.Property> 
      getPropsList();
  /**
   * <code>repeated .emqx.exhook.v2.Property props = 2;</code>
   */
  com.thpower.emqx.java.Property getProps(int index);
  /**
   * <code>repeated .emqx.exhook.v2.Property props = 2;</code>
   */
  int getPropsCount();
  /**
   * <code>repeated .emqx.exhook.v2.Property props = 2;</code>
   */
  java.util.List<? extends com.thpower.emqx.java.PropertyOrBuilder> 
      getPropsOrBuilderList();
  /**
   * <code>repeated .emqx.exhook.v2.Property props = 2;</code>
   */
  com.thpower.emqx.java.PropertyOrBuilder getPropsOrBuilder(
      int index);

  /**
   * <code>repeated .emqx.exhook.v2.TopicFilter topic_filters = 3;</code>
   */
  java.util.List<com.thpower.emqx.java.TopicFilter> 
      getTopicFiltersList();
  /**
   * <code>repeated .emqx.exhook.v2.TopicFilter topic_filters = 3;</code>
   */
  com.thpower.emqx.java.TopicFilter getTopicFilters(int index);
  /**
   * <code>repeated .emqx.exhook.v2.TopicFilter topic_filters = 3;</code>
   */
  int getTopicFiltersCount();
  /**
   * <code>repeated .emqx.exhook.v2.TopicFilter topic_filters = 3;</code>
   */
  java.util.List<? extends com.thpower.emqx.java.TopicFilterOrBuilder> 
      getTopicFiltersOrBuilderList();
  /**
   * <code>repeated .emqx.exhook.v2.TopicFilter topic_filters = 3;</code>
   */
  com.thpower.emqx.java.TopicFilterOrBuilder getTopicFiltersOrBuilder(
      int index);

  /**
   * <code>.emqx.exhook.v2.RequestMeta meta = 4;</code>
   * @return Whether the meta field is set.
   */
  boolean hasMeta();
  /**
   * <code>.emqx.exhook.v2.RequestMeta meta = 4;</code>
   * @return The meta.
   */
  com.thpower.emqx.java.RequestMeta getMeta();
  /**
   * <code>.emqx.exhook.v2.RequestMeta meta = 4;</code>
   */
  com.thpower.emqx.java.RequestMetaOrBuilder getMetaOrBuilder();
}
