// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exhook.proto

package com.thpower.emqx.java;

/**
 * Protobuf type {@code emqx.exhook.v2.ClientConnackRequest}
 */
public final class ClientConnackRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:emqx.exhook.v2.ClientConnackRequest)
    ClientConnackRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ClientConnackRequest.newBuilder() to construct.
  private ClientConnackRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ClientConnackRequest() {
    resultCode_ = "";
    props_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ClientConnackRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ClientConnackRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.thpower.emqx.java.ConnInfo.Builder subBuilder = null;
            if (conninfo_ != null) {
              subBuilder = conninfo_.toBuilder();
            }
            conninfo_ = input.readMessage(com.thpower.emqx.java.ConnInfo.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(conninfo_);
              conninfo_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            resultCode_ = s;
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              props_ = new java.util.ArrayList<com.thpower.emqx.java.Property>();
              mutable_bitField0_ |= 0x00000001;
            }
            props_.add(
                input.readMessage(com.thpower.emqx.java.Property.parser(), extensionRegistry));
            break;
          }
          case 34: {
            com.thpower.emqx.java.RequestMeta.Builder subBuilder = null;
            if (meta_ != null) {
              subBuilder = meta_.toBuilder();
            }
            meta_ = input.readMessage(com.thpower.emqx.java.RequestMeta.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(meta_);
              meta_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        props_ = java.util.Collections.unmodifiableList(props_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.thpower.emqx.java.EmqxExHookProto.internal_static_emqx_exhook_v2_ClientConnackRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.thpower.emqx.java.EmqxExHookProto.internal_static_emqx_exhook_v2_ClientConnackRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.thpower.emqx.java.ClientConnackRequest.class, com.thpower.emqx.java.ClientConnackRequest.Builder.class);
  }

  public static final int CONNINFO_FIELD_NUMBER = 1;
  private com.thpower.emqx.java.ConnInfo conninfo_;
  /**
   * <code>.emqx.exhook.v2.ConnInfo conninfo = 1;</code>
   * @return Whether the conninfo field is set.
   */
  @java.lang.Override
  public boolean hasConninfo() {
    return conninfo_ != null;
  }
  /**
   * <code>.emqx.exhook.v2.ConnInfo conninfo = 1;</code>
   * @return The conninfo.
   */
  @java.lang.Override
  public com.thpower.emqx.java.ConnInfo getConninfo() {
    return conninfo_ == null ? com.thpower.emqx.java.ConnInfo.getDefaultInstance() : conninfo_;
  }
  /**
   * <code>.emqx.exhook.v2.ConnInfo conninfo = 1;</code>
   */
  @java.lang.Override
  public com.thpower.emqx.java.ConnInfoOrBuilder getConninfoOrBuilder() {
    return getConninfo();
  }

  public static final int RESULT_CODE_FIELD_NUMBER = 2;
  private volatile java.lang.Object resultCode_;
  /**
   * <code>string result_code = 2;</code>
   * @return The resultCode.
   */
  @java.lang.Override
  public java.lang.String getResultCode() {
    java.lang.Object ref = resultCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      resultCode_ = s;
      return s;
    }
  }
  /**
   * <code>string result_code = 2;</code>
   * @return The bytes for resultCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getResultCodeBytes() {
    java.lang.Object ref = resultCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      resultCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROPS_FIELD_NUMBER = 3;
  private java.util.List<com.thpower.emqx.java.Property> props_;
  /**
   * <code>repeated .emqx.exhook.v2.Property props = 3;</code>
   */
  @java.lang.Override
  public java.util.List<com.thpower.emqx.java.Property> getPropsList() {
    return props_;
  }
  /**
   * <code>repeated .emqx.exhook.v2.Property props = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.thpower.emqx.java.PropertyOrBuilder> 
      getPropsOrBuilderList() {
    return props_;
  }
  /**
   * <code>repeated .emqx.exhook.v2.Property props = 3;</code>
   */
  @java.lang.Override
  public int getPropsCount() {
    return props_.size();
  }
  /**
   * <code>repeated .emqx.exhook.v2.Property props = 3;</code>
   */
  @java.lang.Override
  public com.thpower.emqx.java.Property getProps(int index) {
    return props_.get(index);
  }
  /**
   * <code>repeated .emqx.exhook.v2.Property props = 3;</code>
   */
  @java.lang.Override
  public com.thpower.emqx.java.PropertyOrBuilder getPropsOrBuilder(
      int index) {
    return props_.get(index);
  }

  public static final int META_FIELD_NUMBER = 4;
  private com.thpower.emqx.java.RequestMeta meta_;
  /**
   * <code>.emqx.exhook.v2.RequestMeta meta = 4;</code>
   * @return Whether the meta field is set.
   */
  @java.lang.Override
  public boolean hasMeta() {
    return meta_ != null;
  }
  /**
   * <code>.emqx.exhook.v2.RequestMeta meta = 4;</code>
   * @return The meta.
   */
  @java.lang.Override
  public com.thpower.emqx.java.RequestMeta getMeta() {
    return meta_ == null ? com.thpower.emqx.java.RequestMeta.getDefaultInstance() : meta_;
  }
  /**
   * <code>.emqx.exhook.v2.RequestMeta meta = 4;</code>
   */
  @java.lang.Override
  public com.thpower.emqx.java.RequestMetaOrBuilder getMetaOrBuilder() {
    return getMeta();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (conninfo_ != null) {
      output.writeMessage(1, getConninfo());
    }
    if (!getResultCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, resultCode_);
    }
    for (int i = 0; i < props_.size(); i++) {
      output.writeMessage(3, props_.get(i));
    }
    if (meta_ != null) {
      output.writeMessage(4, getMeta());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (conninfo_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getConninfo());
    }
    if (!getResultCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, resultCode_);
    }
    for (int i = 0; i < props_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, props_.get(i));
    }
    if (meta_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getMeta());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.thpower.emqx.java.ClientConnackRequest)) {
      return super.equals(obj);
    }
    com.thpower.emqx.java.ClientConnackRequest other = (com.thpower.emqx.java.ClientConnackRequest) obj;

    if (hasConninfo() != other.hasConninfo()) return false;
    if (hasConninfo()) {
      if (!getConninfo()
          .equals(other.getConninfo())) return false;
    }
    if (!getResultCode()
        .equals(other.getResultCode())) return false;
    if (!getPropsList()
        .equals(other.getPropsList())) return false;
    if (hasMeta() != other.hasMeta()) return false;
    if (hasMeta()) {
      if (!getMeta()
          .equals(other.getMeta())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasConninfo()) {
      hash = (37 * hash) + CONNINFO_FIELD_NUMBER;
      hash = (53 * hash) + getConninfo().hashCode();
    }
    hash = (37 * hash) + RESULT_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getResultCode().hashCode();
    if (getPropsCount() > 0) {
      hash = (37 * hash) + PROPS_FIELD_NUMBER;
      hash = (53 * hash) + getPropsList().hashCode();
    }
    if (hasMeta()) {
      hash = (37 * hash) + META_FIELD_NUMBER;
      hash = (53 * hash) + getMeta().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.thpower.emqx.java.ClientConnackRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.thpower.emqx.java.ClientConnackRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.thpower.emqx.java.ClientConnackRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.thpower.emqx.java.ClientConnackRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.thpower.emqx.java.ClientConnackRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.thpower.emqx.java.ClientConnackRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.thpower.emqx.java.ClientConnackRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.thpower.emqx.java.ClientConnackRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.thpower.emqx.java.ClientConnackRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.thpower.emqx.java.ClientConnackRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.thpower.emqx.java.ClientConnackRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.thpower.emqx.java.ClientConnackRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.thpower.emqx.java.ClientConnackRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code emqx.exhook.v2.ClientConnackRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:emqx.exhook.v2.ClientConnackRequest)
      com.thpower.emqx.java.ClientConnackRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.thpower.emqx.java.EmqxExHookProto.internal_static_emqx_exhook_v2_ClientConnackRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.thpower.emqx.java.EmqxExHookProto.internal_static_emqx_exhook_v2_ClientConnackRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.thpower.emqx.java.ClientConnackRequest.class, com.thpower.emqx.java.ClientConnackRequest.Builder.class);
    }

    // Construct using com.thpower.emqx.java.ClientConnackRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPropsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (conninfoBuilder_ == null) {
        conninfo_ = null;
      } else {
        conninfo_ = null;
        conninfoBuilder_ = null;
      }
      resultCode_ = "";

      if (propsBuilder_ == null) {
        props_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        propsBuilder_.clear();
      }
      if (metaBuilder_ == null) {
        meta_ = null;
      } else {
        meta_ = null;
        metaBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.thpower.emqx.java.EmqxExHookProto.internal_static_emqx_exhook_v2_ClientConnackRequest_descriptor;
    }

    @java.lang.Override
    public com.thpower.emqx.java.ClientConnackRequest getDefaultInstanceForType() {
      return com.thpower.emqx.java.ClientConnackRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.thpower.emqx.java.ClientConnackRequest build() {
      com.thpower.emqx.java.ClientConnackRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.thpower.emqx.java.ClientConnackRequest buildPartial() {
      com.thpower.emqx.java.ClientConnackRequest result = new com.thpower.emqx.java.ClientConnackRequest(this);
      int from_bitField0_ = bitField0_;
      if (conninfoBuilder_ == null) {
        result.conninfo_ = conninfo_;
      } else {
        result.conninfo_ = conninfoBuilder_.build();
      }
      result.resultCode_ = resultCode_;
      if (propsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          props_ = java.util.Collections.unmodifiableList(props_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.props_ = props_;
      } else {
        result.props_ = propsBuilder_.build();
      }
      if (metaBuilder_ == null) {
        result.meta_ = meta_;
      } else {
        result.meta_ = metaBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.thpower.emqx.java.ClientConnackRequest) {
        return mergeFrom((com.thpower.emqx.java.ClientConnackRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.thpower.emqx.java.ClientConnackRequest other) {
      if (other == com.thpower.emqx.java.ClientConnackRequest.getDefaultInstance()) return this;
      if (other.hasConninfo()) {
        mergeConninfo(other.getConninfo());
      }
      if (!other.getResultCode().isEmpty()) {
        resultCode_ = other.resultCode_;
        onChanged();
      }
      if (propsBuilder_ == null) {
        if (!other.props_.isEmpty()) {
          if (props_.isEmpty()) {
            props_ = other.props_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePropsIsMutable();
            props_.addAll(other.props_);
          }
          onChanged();
        }
      } else {
        if (!other.props_.isEmpty()) {
          if (propsBuilder_.isEmpty()) {
            propsBuilder_.dispose();
            propsBuilder_ = null;
            props_ = other.props_;
            bitField0_ = (bitField0_ & ~0x00000001);
            propsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPropsFieldBuilder() : null;
          } else {
            propsBuilder_.addAllMessages(other.props_);
          }
        }
      }
      if (other.hasMeta()) {
        mergeMeta(other.getMeta());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.thpower.emqx.java.ClientConnackRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.thpower.emqx.java.ClientConnackRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.thpower.emqx.java.ConnInfo conninfo_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.thpower.emqx.java.ConnInfo, com.thpower.emqx.java.ConnInfo.Builder, com.thpower.emqx.java.ConnInfoOrBuilder> conninfoBuilder_;
    /**
     * <code>.emqx.exhook.v2.ConnInfo conninfo = 1;</code>
     * @return Whether the conninfo field is set.
     */
    public boolean hasConninfo() {
      return conninfoBuilder_ != null || conninfo_ != null;
    }
    /**
     * <code>.emqx.exhook.v2.ConnInfo conninfo = 1;</code>
     * @return The conninfo.
     */
    public com.thpower.emqx.java.ConnInfo getConninfo() {
      if (conninfoBuilder_ == null) {
        return conninfo_ == null ? com.thpower.emqx.java.ConnInfo.getDefaultInstance() : conninfo_;
      } else {
        return conninfoBuilder_.getMessage();
      }
    }
    /**
     * <code>.emqx.exhook.v2.ConnInfo conninfo = 1;</code>
     */
    public Builder setConninfo(com.thpower.emqx.java.ConnInfo value) {
      if (conninfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        conninfo_ = value;
        onChanged();
      } else {
        conninfoBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.emqx.exhook.v2.ConnInfo conninfo = 1;</code>
     */
    public Builder setConninfo(
        com.thpower.emqx.java.ConnInfo.Builder builderForValue) {
      if (conninfoBuilder_ == null) {
        conninfo_ = builderForValue.build();
        onChanged();
      } else {
        conninfoBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.emqx.exhook.v2.ConnInfo conninfo = 1;</code>
     */
    public Builder mergeConninfo(com.thpower.emqx.java.ConnInfo value) {
      if (conninfoBuilder_ == null) {
        if (conninfo_ != null) {
          conninfo_ =
            com.thpower.emqx.java.ConnInfo.newBuilder(conninfo_).mergeFrom(value).buildPartial();
        } else {
          conninfo_ = value;
        }
        onChanged();
      } else {
        conninfoBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.emqx.exhook.v2.ConnInfo conninfo = 1;</code>
     */
    public Builder clearConninfo() {
      if (conninfoBuilder_ == null) {
        conninfo_ = null;
        onChanged();
      } else {
        conninfo_ = null;
        conninfoBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.emqx.exhook.v2.ConnInfo conninfo = 1;</code>
     */
    public com.thpower.emqx.java.ConnInfo.Builder getConninfoBuilder() {
      
      onChanged();
      return getConninfoFieldBuilder().getBuilder();
    }
    /**
     * <code>.emqx.exhook.v2.ConnInfo conninfo = 1;</code>
     */
    public com.thpower.emqx.java.ConnInfoOrBuilder getConninfoOrBuilder() {
      if (conninfoBuilder_ != null) {
        return conninfoBuilder_.getMessageOrBuilder();
      } else {
        return conninfo_ == null ?
            com.thpower.emqx.java.ConnInfo.getDefaultInstance() : conninfo_;
      }
    }
    /**
     * <code>.emqx.exhook.v2.ConnInfo conninfo = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.thpower.emqx.java.ConnInfo, com.thpower.emqx.java.ConnInfo.Builder, com.thpower.emqx.java.ConnInfoOrBuilder> 
        getConninfoFieldBuilder() {
      if (conninfoBuilder_ == null) {
        conninfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.thpower.emqx.java.ConnInfo, com.thpower.emqx.java.ConnInfo.Builder, com.thpower.emqx.java.ConnInfoOrBuilder>(
                getConninfo(),
                getParentForChildren(),
                isClean());
        conninfo_ = null;
      }
      return conninfoBuilder_;
    }

    private java.lang.Object resultCode_ = "";
    /**
     * <code>string result_code = 2;</code>
     * @return The resultCode.
     */
    public java.lang.String getResultCode() {
      java.lang.Object ref = resultCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        resultCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string result_code = 2;</code>
     * @return The bytes for resultCode.
     */
    public com.google.protobuf.ByteString
        getResultCodeBytes() {
      java.lang.Object ref = resultCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resultCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string result_code = 2;</code>
     * @param value The resultCode to set.
     * @return This builder for chaining.
     */
    public Builder setResultCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      resultCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string result_code = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearResultCode() {
      
      resultCode_ = getDefaultInstance().getResultCode();
      onChanged();
      return this;
    }
    /**
     * <code>string result_code = 2;</code>
     * @param value The bytes for resultCode to set.
     * @return This builder for chaining.
     */
    public Builder setResultCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      resultCode_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.thpower.emqx.java.Property> props_ =
      java.util.Collections.emptyList();
    private void ensurePropsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        props_ = new java.util.ArrayList<com.thpower.emqx.java.Property>(props_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.thpower.emqx.java.Property, com.thpower.emqx.java.Property.Builder, com.thpower.emqx.java.PropertyOrBuilder> propsBuilder_;

    /**
     * <code>repeated .emqx.exhook.v2.Property props = 3;</code>
     */
    public java.util.List<com.thpower.emqx.java.Property> getPropsList() {
      if (propsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(props_);
      } else {
        return propsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .emqx.exhook.v2.Property props = 3;</code>
     */
    public int getPropsCount() {
      if (propsBuilder_ == null) {
        return props_.size();
      } else {
        return propsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .emqx.exhook.v2.Property props = 3;</code>
     */
    public com.thpower.emqx.java.Property getProps(int index) {
      if (propsBuilder_ == null) {
        return props_.get(index);
      } else {
        return propsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .emqx.exhook.v2.Property props = 3;</code>
     */
    public Builder setProps(
        int index, com.thpower.emqx.java.Property value) {
      if (propsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePropsIsMutable();
        props_.set(index, value);
        onChanged();
      } else {
        propsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .emqx.exhook.v2.Property props = 3;</code>
     */
    public Builder setProps(
        int index, com.thpower.emqx.java.Property.Builder builderForValue) {
      if (propsBuilder_ == null) {
        ensurePropsIsMutable();
        props_.set(index, builderForValue.build());
        onChanged();
      } else {
        propsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .emqx.exhook.v2.Property props = 3;</code>
     */
    public Builder addProps(com.thpower.emqx.java.Property value) {
      if (propsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePropsIsMutable();
        props_.add(value);
        onChanged();
      } else {
        propsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .emqx.exhook.v2.Property props = 3;</code>
     */
    public Builder addProps(
        int index, com.thpower.emqx.java.Property value) {
      if (propsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePropsIsMutable();
        props_.add(index, value);
        onChanged();
      } else {
        propsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .emqx.exhook.v2.Property props = 3;</code>
     */
    public Builder addProps(
        com.thpower.emqx.java.Property.Builder builderForValue) {
      if (propsBuilder_ == null) {
        ensurePropsIsMutable();
        props_.add(builderForValue.build());
        onChanged();
      } else {
        propsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .emqx.exhook.v2.Property props = 3;</code>
     */
    public Builder addProps(
        int index, com.thpower.emqx.java.Property.Builder builderForValue) {
      if (propsBuilder_ == null) {
        ensurePropsIsMutable();
        props_.add(index, builderForValue.build());
        onChanged();
      } else {
        propsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .emqx.exhook.v2.Property props = 3;</code>
     */
    public Builder addAllProps(
        java.lang.Iterable<? extends com.thpower.emqx.java.Property> values) {
      if (propsBuilder_ == null) {
        ensurePropsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, props_);
        onChanged();
      } else {
        propsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .emqx.exhook.v2.Property props = 3;</code>
     */
    public Builder clearProps() {
      if (propsBuilder_ == null) {
        props_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        propsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .emqx.exhook.v2.Property props = 3;</code>
     */
    public Builder removeProps(int index) {
      if (propsBuilder_ == null) {
        ensurePropsIsMutable();
        props_.remove(index);
        onChanged();
      } else {
        propsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .emqx.exhook.v2.Property props = 3;</code>
     */
    public com.thpower.emqx.java.Property.Builder getPropsBuilder(
        int index) {
      return getPropsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .emqx.exhook.v2.Property props = 3;</code>
     */
    public com.thpower.emqx.java.PropertyOrBuilder getPropsOrBuilder(
        int index) {
      if (propsBuilder_ == null) {
        return props_.get(index);  } else {
        return propsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .emqx.exhook.v2.Property props = 3;</code>
     */
    public java.util.List<? extends com.thpower.emqx.java.PropertyOrBuilder> 
         getPropsOrBuilderList() {
      if (propsBuilder_ != null) {
        return propsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(props_);
      }
    }
    /**
     * <code>repeated .emqx.exhook.v2.Property props = 3;</code>
     */
    public com.thpower.emqx.java.Property.Builder addPropsBuilder() {
      return getPropsFieldBuilder().addBuilder(
          com.thpower.emqx.java.Property.getDefaultInstance());
    }
    /**
     * <code>repeated .emqx.exhook.v2.Property props = 3;</code>
     */
    public com.thpower.emqx.java.Property.Builder addPropsBuilder(
        int index) {
      return getPropsFieldBuilder().addBuilder(
          index, com.thpower.emqx.java.Property.getDefaultInstance());
    }
    /**
     * <code>repeated .emqx.exhook.v2.Property props = 3;</code>
     */
    public java.util.List<com.thpower.emqx.java.Property.Builder> 
         getPropsBuilderList() {
      return getPropsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.thpower.emqx.java.Property, com.thpower.emqx.java.Property.Builder, com.thpower.emqx.java.PropertyOrBuilder> 
        getPropsFieldBuilder() {
      if (propsBuilder_ == null) {
        propsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.thpower.emqx.java.Property, com.thpower.emqx.java.Property.Builder, com.thpower.emqx.java.PropertyOrBuilder>(
                props_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        props_ = null;
      }
      return propsBuilder_;
    }

    private com.thpower.emqx.java.RequestMeta meta_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.thpower.emqx.java.RequestMeta, com.thpower.emqx.java.RequestMeta.Builder, com.thpower.emqx.java.RequestMetaOrBuilder> metaBuilder_;
    /**
     * <code>.emqx.exhook.v2.RequestMeta meta = 4;</code>
     * @return Whether the meta field is set.
     */
    public boolean hasMeta() {
      return metaBuilder_ != null || meta_ != null;
    }
    /**
     * <code>.emqx.exhook.v2.RequestMeta meta = 4;</code>
     * @return The meta.
     */
    public com.thpower.emqx.java.RequestMeta getMeta() {
      if (metaBuilder_ == null) {
        return meta_ == null ? com.thpower.emqx.java.RequestMeta.getDefaultInstance() : meta_;
      } else {
        return metaBuilder_.getMessage();
      }
    }
    /**
     * <code>.emqx.exhook.v2.RequestMeta meta = 4;</code>
     */
    public Builder setMeta(com.thpower.emqx.java.RequestMeta value) {
      if (metaBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        meta_ = value;
        onChanged();
      } else {
        metaBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.emqx.exhook.v2.RequestMeta meta = 4;</code>
     */
    public Builder setMeta(
        com.thpower.emqx.java.RequestMeta.Builder builderForValue) {
      if (metaBuilder_ == null) {
        meta_ = builderForValue.build();
        onChanged();
      } else {
        metaBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.emqx.exhook.v2.RequestMeta meta = 4;</code>
     */
    public Builder mergeMeta(com.thpower.emqx.java.RequestMeta value) {
      if (metaBuilder_ == null) {
        if (meta_ != null) {
          meta_ =
            com.thpower.emqx.java.RequestMeta.newBuilder(meta_).mergeFrom(value).buildPartial();
        } else {
          meta_ = value;
        }
        onChanged();
      } else {
        metaBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.emqx.exhook.v2.RequestMeta meta = 4;</code>
     */
    public Builder clearMeta() {
      if (metaBuilder_ == null) {
        meta_ = null;
        onChanged();
      } else {
        meta_ = null;
        metaBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.emqx.exhook.v2.RequestMeta meta = 4;</code>
     */
    public com.thpower.emqx.java.RequestMeta.Builder getMetaBuilder() {
      
      onChanged();
      return getMetaFieldBuilder().getBuilder();
    }
    /**
     * <code>.emqx.exhook.v2.RequestMeta meta = 4;</code>
     */
    public com.thpower.emqx.java.RequestMetaOrBuilder getMetaOrBuilder() {
      if (metaBuilder_ != null) {
        return metaBuilder_.getMessageOrBuilder();
      } else {
        return meta_ == null ?
            com.thpower.emqx.java.RequestMeta.getDefaultInstance() : meta_;
      }
    }
    /**
     * <code>.emqx.exhook.v2.RequestMeta meta = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.thpower.emqx.java.RequestMeta, com.thpower.emqx.java.RequestMeta.Builder, com.thpower.emqx.java.RequestMetaOrBuilder> 
        getMetaFieldBuilder() {
      if (metaBuilder_ == null) {
        metaBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.thpower.emqx.java.RequestMeta, com.thpower.emqx.java.RequestMeta.Builder, com.thpower.emqx.java.RequestMetaOrBuilder>(
                getMeta(),
                getParentForChildren(),
                isClean());
        meta_ = null;
      }
      return metaBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:emqx.exhook.v2.ClientConnackRequest)
  }

  // @@protoc_insertion_point(class_scope:emqx.exhook.v2.ClientConnackRequest)
  private static final com.thpower.emqx.java.ClientConnackRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.thpower.emqx.java.ClientConnackRequest();
  }

  public static com.thpower.emqx.java.ClientConnackRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ClientConnackRequest>
      PARSER = new com.google.protobuf.AbstractParser<ClientConnackRequest>() {
    @java.lang.Override
    public ClientConnackRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ClientConnackRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ClientConnackRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ClientConnackRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.thpower.emqx.java.ClientConnackRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

