// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exhook.proto

package com.thpower.emqx.java;

public interface EmptySuccessOrBuilder extends
    // @@protoc_insertion_point(interface_extends:emqx.exhook.v2.EmptySuccess)
    com.google.protobuf.MessageOrBuilder {
}
