// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exhook.proto

package com.thpower.emqx.java;

public interface LoadedResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:emqx.exhook.v2.LoadedResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .emqx.exhook.v2.HookSpec hooks = 1;</code>
   */
  java.util.List<com.thpower.emqx.java.HookSpec> 
      getHooksList();
  /**
   * <code>repeated .emqx.exhook.v2.HookSpec hooks = 1;</code>
   */
  com.thpower.emqx.java.HookSpec getHooks(int index);
  /**
   * <code>repeated .emqx.exhook.v2.HookSpec hooks = 1;</code>
   */
  int getHooksCount();
  /**
   * <code>repeated .emqx.exhook.v2.HookSpec hooks = 1;</code>
   */
  java.util.List<? extends com.thpower.emqx.java.HookSpecOrBuilder> 
      getHooksOrBuilderList();
  /**
   * <code>repeated .emqx.exhook.v2.HookSpec hooks = 1;</code>
   */
  com.thpower.emqx.java.HookSpecOrBuilder getHooksOrBuilder(
      int index);
}
