// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exhook.proto

package com.thpower.emqx.java;

/**
 * Protobuf type {@code emqx.exhook.v2.ProviderLoadedRequest}
 */
public final class ProviderLoadedRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:emqx.exhook.v2.ProviderLoadedRequest)
    ProviderLoadedRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ProviderLoadedRequest.newBuilder() to construct.
  private ProviderLoadedRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ProviderLoadedRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ProviderLoadedRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ProviderLoadedRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.thpower.emqx.java.BrokerInfo.Builder subBuilder = null;
            if (broker_ != null) {
              subBuilder = broker_.toBuilder();
            }
            broker_ = input.readMessage(com.thpower.emqx.java.BrokerInfo.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(broker_);
              broker_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.thpower.emqx.java.RequestMeta.Builder subBuilder = null;
            if (meta_ != null) {
              subBuilder = meta_.toBuilder();
            }
            meta_ = input.readMessage(com.thpower.emqx.java.RequestMeta.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(meta_);
              meta_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.thpower.emqx.java.EmqxExHookProto.internal_static_emqx_exhook_v2_ProviderLoadedRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.thpower.emqx.java.EmqxExHookProto.internal_static_emqx_exhook_v2_ProviderLoadedRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.thpower.emqx.java.ProviderLoadedRequest.class, com.thpower.emqx.java.ProviderLoadedRequest.Builder.class);
  }

  public static final int BROKER_FIELD_NUMBER = 1;
  private com.thpower.emqx.java.BrokerInfo broker_;
  /**
   * <code>.emqx.exhook.v2.BrokerInfo broker = 1;</code>
   * @return Whether the broker field is set.
   */
  @java.lang.Override
  public boolean hasBroker() {
    return broker_ != null;
  }
  /**
   * <code>.emqx.exhook.v2.BrokerInfo broker = 1;</code>
   * @return The broker.
   */
  @java.lang.Override
  public com.thpower.emqx.java.BrokerInfo getBroker() {
    return broker_ == null ? com.thpower.emqx.java.BrokerInfo.getDefaultInstance() : broker_;
  }
  /**
   * <code>.emqx.exhook.v2.BrokerInfo broker = 1;</code>
   */
  @java.lang.Override
  public com.thpower.emqx.java.BrokerInfoOrBuilder getBrokerOrBuilder() {
    return getBroker();
  }

  public static final int META_FIELD_NUMBER = 2;
  private com.thpower.emqx.java.RequestMeta meta_;
  /**
   * <code>.emqx.exhook.v2.RequestMeta meta = 2;</code>
   * @return Whether the meta field is set.
   */
  @java.lang.Override
  public boolean hasMeta() {
    return meta_ != null;
  }
  /**
   * <code>.emqx.exhook.v2.RequestMeta meta = 2;</code>
   * @return The meta.
   */
  @java.lang.Override
  public com.thpower.emqx.java.RequestMeta getMeta() {
    return meta_ == null ? com.thpower.emqx.java.RequestMeta.getDefaultInstance() : meta_;
  }
  /**
   * <code>.emqx.exhook.v2.RequestMeta meta = 2;</code>
   */
  @java.lang.Override
  public com.thpower.emqx.java.RequestMetaOrBuilder getMetaOrBuilder() {
    return getMeta();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (broker_ != null) {
      output.writeMessage(1, getBroker());
    }
    if (meta_ != null) {
      output.writeMessage(2, getMeta());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (broker_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getBroker());
    }
    if (meta_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getMeta());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.thpower.emqx.java.ProviderLoadedRequest)) {
      return super.equals(obj);
    }
    com.thpower.emqx.java.ProviderLoadedRequest other = (com.thpower.emqx.java.ProviderLoadedRequest) obj;

    if (hasBroker() != other.hasBroker()) return false;
    if (hasBroker()) {
      if (!getBroker()
          .equals(other.getBroker())) return false;
    }
    if (hasMeta() != other.hasMeta()) return false;
    if (hasMeta()) {
      if (!getMeta()
          .equals(other.getMeta())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasBroker()) {
      hash = (37 * hash) + BROKER_FIELD_NUMBER;
      hash = (53 * hash) + getBroker().hashCode();
    }
    if (hasMeta()) {
      hash = (37 * hash) + META_FIELD_NUMBER;
      hash = (53 * hash) + getMeta().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.thpower.emqx.java.ProviderLoadedRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.thpower.emqx.java.ProviderLoadedRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.thpower.emqx.java.ProviderLoadedRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.thpower.emqx.java.ProviderLoadedRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.thpower.emqx.java.ProviderLoadedRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.thpower.emqx.java.ProviderLoadedRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.thpower.emqx.java.ProviderLoadedRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.thpower.emqx.java.ProviderLoadedRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.thpower.emqx.java.ProviderLoadedRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.thpower.emqx.java.ProviderLoadedRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.thpower.emqx.java.ProviderLoadedRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.thpower.emqx.java.ProviderLoadedRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.thpower.emqx.java.ProviderLoadedRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code emqx.exhook.v2.ProviderLoadedRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:emqx.exhook.v2.ProviderLoadedRequest)
      com.thpower.emqx.java.ProviderLoadedRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.thpower.emqx.java.EmqxExHookProto.internal_static_emqx_exhook_v2_ProviderLoadedRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.thpower.emqx.java.EmqxExHookProto.internal_static_emqx_exhook_v2_ProviderLoadedRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.thpower.emqx.java.ProviderLoadedRequest.class, com.thpower.emqx.java.ProviderLoadedRequest.Builder.class);
    }

    // Construct using com.thpower.emqx.java.ProviderLoadedRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (brokerBuilder_ == null) {
        broker_ = null;
      } else {
        broker_ = null;
        brokerBuilder_ = null;
      }
      if (metaBuilder_ == null) {
        meta_ = null;
      } else {
        meta_ = null;
        metaBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.thpower.emqx.java.EmqxExHookProto.internal_static_emqx_exhook_v2_ProviderLoadedRequest_descriptor;
    }

    @java.lang.Override
    public com.thpower.emqx.java.ProviderLoadedRequest getDefaultInstanceForType() {
      return com.thpower.emqx.java.ProviderLoadedRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.thpower.emqx.java.ProviderLoadedRequest build() {
      com.thpower.emqx.java.ProviderLoadedRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.thpower.emqx.java.ProviderLoadedRequest buildPartial() {
      com.thpower.emqx.java.ProviderLoadedRequest result = new com.thpower.emqx.java.ProviderLoadedRequest(this);
      if (brokerBuilder_ == null) {
        result.broker_ = broker_;
      } else {
        result.broker_ = brokerBuilder_.build();
      }
      if (metaBuilder_ == null) {
        result.meta_ = meta_;
      } else {
        result.meta_ = metaBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.thpower.emqx.java.ProviderLoadedRequest) {
        return mergeFrom((com.thpower.emqx.java.ProviderLoadedRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.thpower.emqx.java.ProviderLoadedRequest other) {
      if (other == com.thpower.emqx.java.ProviderLoadedRequest.getDefaultInstance()) return this;
      if (other.hasBroker()) {
        mergeBroker(other.getBroker());
      }
      if (other.hasMeta()) {
        mergeMeta(other.getMeta());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.thpower.emqx.java.ProviderLoadedRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.thpower.emqx.java.ProviderLoadedRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.thpower.emqx.java.BrokerInfo broker_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.thpower.emqx.java.BrokerInfo, com.thpower.emqx.java.BrokerInfo.Builder, com.thpower.emqx.java.BrokerInfoOrBuilder> brokerBuilder_;
    /**
     * <code>.emqx.exhook.v2.BrokerInfo broker = 1;</code>
     * @return Whether the broker field is set.
     */
    public boolean hasBroker() {
      return brokerBuilder_ != null || broker_ != null;
    }
    /**
     * <code>.emqx.exhook.v2.BrokerInfo broker = 1;</code>
     * @return The broker.
     */
    public com.thpower.emqx.java.BrokerInfo getBroker() {
      if (brokerBuilder_ == null) {
        return broker_ == null ? com.thpower.emqx.java.BrokerInfo.getDefaultInstance() : broker_;
      } else {
        return brokerBuilder_.getMessage();
      }
    }
    /**
     * <code>.emqx.exhook.v2.BrokerInfo broker = 1;</code>
     */
    public Builder setBroker(com.thpower.emqx.java.BrokerInfo value) {
      if (brokerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        broker_ = value;
        onChanged();
      } else {
        brokerBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.emqx.exhook.v2.BrokerInfo broker = 1;</code>
     */
    public Builder setBroker(
        com.thpower.emqx.java.BrokerInfo.Builder builderForValue) {
      if (brokerBuilder_ == null) {
        broker_ = builderForValue.build();
        onChanged();
      } else {
        brokerBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.emqx.exhook.v2.BrokerInfo broker = 1;</code>
     */
    public Builder mergeBroker(com.thpower.emqx.java.BrokerInfo value) {
      if (brokerBuilder_ == null) {
        if (broker_ != null) {
          broker_ =
            com.thpower.emqx.java.BrokerInfo.newBuilder(broker_).mergeFrom(value).buildPartial();
        } else {
          broker_ = value;
        }
        onChanged();
      } else {
        brokerBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.emqx.exhook.v2.BrokerInfo broker = 1;</code>
     */
    public Builder clearBroker() {
      if (brokerBuilder_ == null) {
        broker_ = null;
        onChanged();
      } else {
        broker_ = null;
        brokerBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.emqx.exhook.v2.BrokerInfo broker = 1;</code>
     */
    public com.thpower.emqx.java.BrokerInfo.Builder getBrokerBuilder() {
      
      onChanged();
      return getBrokerFieldBuilder().getBuilder();
    }
    /**
     * <code>.emqx.exhook.v2.BrokerInfo broker = 1;</code>
     */
    public com.thpower.emqx.java.BrokerInfoOrBuilder getBrokerOrBuilder() {
      if (brokerBuilder_ != null) {
        return brokerBuilder_.getMessageOrBuilder();
      } else {
        return broker_ == null ?
            com.thpower.emqx.java.BrokerInfo.getDefaultInstance() : broker_;
      }
    }
    /**
     * <code>.emqx.exhook.v2.BrokerInfo broker = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.thpower.emqx.java.BrokerInfo, com.thpower.emqx.java.BrokerInfo.Builder, com.thpower.emqx.java.BrokerInfoOrBuilder> 
        getBrokerFieldBuilder() {
      if (brokerBuilder_ == null) {
        brokerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.thpower.emqx.java.BrokerInfo, com.thpower.emqx.java.BrokerInfo.Builder, com.thpower.emqx.java.BrokerInfoOrBuilder>(
                getBroker(),
                getParentForChildren(),
                isClean());
        broker_ = null;
      }
      return brokerBuilder_;
    }

    private com.thpower.emqx.java.RequestMeta meta_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.thpower.emqx.java.RequestMeta, com.thpower.emqx.java.RequestMeta.Builder, com.thpower.emqx.java.RequestMetaOrBuilder> metaBuilder_;
    /**
     * <code>.emqx.exhook.v2.RequestMeta meta = 2;</code>
     * @return Whether the meta field is set.
     */
    public boolean hasMeta() {
      return metaBuilder_ != null || meta_ != null;
    }
    /**
     * <code>.emqx.exhook.v2.RequestMeta meta = 2;</code>
     * @return The meta.
     */
    public com.thpower.emqx.java.RequestMeta getMeta() {
      if (metaBuilder_ == null) {
        return meta_ == null ? com.thpower.emqx.java.RequestMeta.getDefaultInstance() : meta_;
      } else {
        return metaBuilder_.getMessage();
      }
    }
    /**
     * <code>.emqx.exhook.v2.RequestMeta meta = 2;</code>
     */
    public Builder setMeta(com.thpower.emqx.java.RequestMeta value) {
      if (metaBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        meta_ = value;
        onChanged();
      } else {
        metaBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.emqx.exhook.v2.RequestMeta meta = 2;</code>
     */
    public Builder setMeta(
        com.thpower.emqx.java.RequestMeta.Builder builderForValue) {
      if (metaBuilder_ == null) {
        meta_ = builderForValue.build();
        onChanged();
      } else {
        metaBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.emqx.exhook.v2.RequestMeta meta = 2;</code>
     */
    public Builder mergeMeta(com.thpower.emqx.java.RequestMeta value) {
      if (metaBuilder_ == null) {
        if (meta_ != null) {
          meta_ =
            com.thpower.emqx.java.RequestMeta.newBuilder(meta_).mergeFrom(value).buildPartial();
        } else {
          meta_ = value;
        }
        onChanged();
      } else {
        metaBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.emqx.exhook.v2.RequestMeta meta = 2;</code>
     */
    public Builder clearMeta() {
      if (metaBuilder_ == null) {
        meta_ = null;
        onChanged();
      } else {
        meta_ = null;
        metaBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.emqx.exhook.v2.RequestMeta meta = 2;</code>
     */
    public com.thpower.emqx.java.RequestMeta.Builder getMetaBuilder() {
      
      onChanged();
      return getMetaFieldBuilder().getBuilder();
    }
    /**
     * <code>.emqx.exhook.v2.RequestMeta meta = 2;</code>
     */
    public com.thpower.emqx.java.RequestMetaOrBuilder getMetaOrBuilder() {
      if (metaBuilder_ != null) {
        return metaBuilder_.getMessageOrBuilder();
      } else {
        return meta_ == null ?
            com.thpower.emqx.java.RequestMeta.getDefaultInstance() : meta_;
      }
    }
    /**
     * <code>.emqx.exhook.v2.RequestMeta meta = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.thpower.emqx.java.RequestMeta, com.thpower.emqx.java.RequestMeta.Builder, com.thpower.emqx.java.RequestMetaOrBuilder> 
        getMetaFieldBuilder() {
      if (metaBuilder_ == null) {
        metaBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.thpower.emqx.java.RequestMeta, com.thpower.emqx.java.RequestMeta.Builder, com.thpower.emqx.java.RequestMetaOrBuilder>(
                getMeta(),
                getParentForChildren(),
                isClean());
        meta_ = null;
      }
      return metaBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:emqx.exhook.v2.ProviderLoadedRequest)
  }

  // @@protoc_insertion_point(class_scope:emqx.exhook.v2.ProviderLoadedRequest)
  private static final com.thpower.emqx.java.ProviderLoadedRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.thpower.emqx.java.ProviderLoadedRequest();
  }

  public static com.thpower.emqx.java.ProviderLoadedRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProviderLoadedRequest>
      PARSER = new com.google.protobuf.AbstractParser<ProviderLoadedRequest>() {
    @java.lang.Override
    public ProviderLoadedRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ProviderLoadedRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ProviderLoadedRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProviderLoadedRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.thpower.emqx.java.ProviderLoadedRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

