// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exhook.proto

package com.thpower.emqx.java;

public interface RequestMetaOrBuilder extends
    // @@protoc_insertion_point(interface_extends:emqx.exhook.v2.RequestMeta)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string node = 1;</code>
   * @return The node.
   */
  java.lang.String getNode();
  /**
   * <code>string node = 1;</code>
   * @return The bytes for node.
   */
  com.google.protobuf.ByteString
      getNodeBytes();

  /**
   * <code>string version = 2;</code>
   * @return The version.
   */
  java.lang.String getVersion();
  /**
   * <code>string version = 2;</code>
   * @return The bytes for version.
   */
  com.google.protobuf.ByteString
      getVersionBytes();

  /**
   * <code>string sysdescr = 3;</code>
   * @return The sysdescr.
   */
  java.lang.String getSysdescr();
  /**
   * <code>string sysdescr = 3;</code>
   * @return The bytes for sysdescr.
   */
  com.google.protobuf.ByteString
      getSysdescrBytes();

  /**
   * <code>string cluster_name = 4;</code>
   * @return The clusterName.
   */
  java.lang.String getClusterName();
  /**
   * <code>string cluster_name = 4;</code>
   * @return The bytes for clusterName.
   */
  com.google.protobuf.ByteString
      getClusterNameBytes();
}
