// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exhook.proto

package com.thpower.emqx.java;

public interface TopicFilterOrBuilder extends
    // @@protoc_insertion_point(interface_extends:emqx.exhook.v2.TopicFilter)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>uint32 qos = 2;</code>
   * @return The qos.
   */
  int getQos();
}
